name: parallax_sensors_bg_example
description: Demo of the library parallax_sensors_bg

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  parallax_sensors_bg:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/example1/
    - assets/example2/
