name: parallax_sensors_bg
description: Flutter package to simplify giving a parallax effect in the background of a page that responds to a corresponding sensor detection.
version: 2.0.0
repository: https://github.com/Prayag-X/parallax_sensors_bg
issue_tracker: https://github.com/Prayag-X/parallax_sensors_bg/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:

platforms:
  android:
  ios:
